name: Update README and Deploy to Gigalixir (Python)

on:
  workflow_dispatch:
  schedule:
    # CRON 表达式，表示每隔20天在UTC时间0点0分运行一次
    # (在每个月的1号和21号运行)
    - cron: '0 0 1,21 * *'

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest
    
    # --- 新增内容：在这里为整个 job 授予权限 ---
    permissions:
      contents: write # 授予对仓库内容（代码）的写入权限

    steps:
      # 第一步：检出你的仓库代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 第二步：设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 第三步：更新 README.md (请根据你的需求修改)
      - name: Update README
        run: |
          echo "Last updated on $(date)" >> README.md

      # 第四步：提交 README 的更改
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          if [[ -z $(git status -s) ]]; then
            echo "No changes to commit. Skipping deployment."
            # 我们在这里创建一个标志位文件，以便后续步骤可以检查是否需要执行
            # 直接 exit 会让 job 状态变为 "cancelled"，可能会引起困惑
            touch .no_changes 
          else
            git add README.md
            git commit -m "docs: auto-update README"
            git push
          fi

      # 第五步：安装 Gigalixir CLI 并配置环境
      - name: Install and Configure Gigalixir CLI
        # 仅在有代码变更时运行此步骤
        if: "! steps.commit.outputs.no_changes"
        run: |
          pip3 install gigalixir --user
          echo "$(python3 -m site --user-base)/bin" >> $GITHUB_PATH

      # 第六步：登录并部署到 Gigalixir
      - name: Login and Deploy to Gigalixir
        # 仅在有代码变更时运行此步骤
        if: "! steps.commit.outputs.no_changes"
        env:
          GIGALIXIR_USERNAME: ${{ secrets.GIGALIXIR_USERNAME }}
          GIGALIXIR_PASSWORD: ${{ secrets.GIGALIXIR_PASSWORD }}
        run: |
          gigalixir login -e "$GIGALIXIR_USERNAME" -p "$GIGALIXIR_PASSWORD"
          gigalixir git:remote nz2 # 确保 'nz2' 是你的 App 名称
          git push -f gigalixir HEAD:master
